### ISSUE TITLE
Minor Corrections/Clarifications - AetherSX2 and Mesen

### ISSUE THREAD

**Issue by MrSujano** [DerekTurtleRoe/awesome-emulators#10]
I might have missed a few things:
- AetherSX2 is partially closed source (PCSX2 portion is open source - hence the existence of PurpleSX2)
https://archive.org/details/aethersx2-libemucore.tar / https://github.com/MrPurple666/AetherSX2
- Under NES:
           [Mesen](https://github.com/SourMesen/Mesen) ([deprecated in favor of Mesen](https://github.com/SourMesen/Mesen2))
           [Mesen-X](https://github.com/NovaSquirrel/Mesen-X) ([deprecated in favor of Mesen](https://github.com/SourMesen/Mesen2))
- For clarification, both should possibly read something along the lines of:  "depreciated in favor of Mesen2" or maybe "Mesen2/Mesen" or maybe even just change the first instance of: [Mesen](https://github.com/SourMesen/Mesen2) ([continued version of this archived Mesen](https://github.com/SourMesen/Mesen))

Thoughts?

**Comment by DerekTurtleRoe** [comment]
@MrSujano Hello! Thanks for the issue! 😄 

Firstly, I had no idea that any source had been released for AetherSX2, so thank you for the link, I will fix that today! 😃 

I will also add PurpleSX2 as well, I didn't know there had been a fork! Very cool.

As for the clarifications about Mesen, "Mesen2" isn't technically a sequel, but a continuation of the original Mesen project in a different repository to keep the history on the old repo. I spoke with several members of the ares community as well as members of the Mesen community as to better understand the differences, and they said they wanted me to clarify that those older repos are archived and no longer active, as well as specifically mentioning to me that I shouldn't label anything "Mesen2" since as I said above, it isn't a sequel, but a continuation of the existing project. Having said that, I did want to include links to those repos for historical context as well as that is where the archived previous releases are. I did tell them that listing all of them without the 2 would be confusing, and they also said that if I did it with the 2 it could still be confusing since it would be seen as a different project even though it isn't really.

But basically, Mesen and Mesen-S were the original projects, then the community forked Mesen and Mesen-S into Mesen-X and Mesen-SX to continue them after the original developer decided to leave the projects. Later he decided to come back, and so Mesen-X and Mesen-SX released their final versions and archived those repos. The original repos were also archived, and a new repo was opened. That is the latest and most updated version of Mesen, but you can't have a repo with the same name as another project, so it had to be called "Mesen2". Hopefully that all makes sense.

I will admit having talked about it extensively with community members, there seems to be no way to make it all make sense to everybody, without sacrificing historical/preservation goals I set out when making the list.

Anyway, sorry for the wall of text and hope all that makes sense, my goal isn't just listing good emulators or notable emulators, but the document serves as a preservation of the history of emulation. 😄 

The issues with AetherSX2 and PurpleSX2 have been resolved hopefully, lemme know what you think! 😄

**Comment by MrSujano** [comment]
Completely understand about the confusion surrounding the continuation of Mesen. I guess the easy way for everyone to distinguish is just to avoid the repo that says "Archived" lol. Thanks for the response and the investigation :)
