### ISSUE TITLE
Compatibility pages links  

### ISSUE THREAD

**Issue by github-user1112** [DerekTurtleRoe/awesome-emulators#11]
Maybe adding links to compatibility pages and something that says how many games it runs with or just a general label on compatibility such as "good", "great", "bad" etc?

**Comment by DerekTurtleRoe** [comment]
@github-user1112 I've been suggested this a lot, but compatibility for many systems is incredibly hard to measure/quantify.

Some emulators can run many games, but aren't accurate. Some can't run many games at all, but they are very accurate. Not to mention "playable" is a subjective definition in some cases, some people considered ZSNES perfectly playable (including myself a long time ago), but the opinion of what is compatible, accurate, and playable changes.

I am heavily considering an accuracy/compatibility column, but I don't want to rush it. I want to take the time to do research and make sure if I do it I do it right. I have always wanted to do something akin to an accuracy testing database or something which tests different emulators, and maybe that is something I should look into instead of putting onto this list, I don't know.

I'll think about it, is the TL;DR. 😅

**Comment by DerekTurtleRoe** [comment]
I've decided that a compatibility and/or accuracy column or section is out of the scope for this project. Sorry.
