### ISSUE TITLE
Missing iOS emulators

### ISSUE THREAD

**Issue by array-in-a-matrix** [DerekTurtleRoe/awesome-emulators#25]
**Is your feature request related to a problem? Please describe.**
Some emulators for iOS are missing and some emulators work on iOS but not marked as such.

**Describe the solution you'd like**
Some missing emulators are listed below:

- [x] - RetroArch* (has iOS port) https://docs.libretro.com/guides/install-ios/#downloading
- [x] - dolphiniOS (dolphin port to iOS) https://dolphinios.oatmealdome.me/ https://github.com/OatmealDome/dolphin-ios
- [x] - PPSSPP* (has iOS port)
- [x] - Provenance Emu* https://provenance-emu.com/
- [x] - Delta emulator* https://deltaemulatorapp.com/
- [x] - https://ds.44670.org/ (web based)
- [x] - https://gba.44670.org/ (web based) https://github.com/44670/44vba

Add to emulation services:
- [x] - https://afterplay.io/

Can't add:
~~Happy Chick https://www.xiaoji001.org/~~

**Additional context**
Started emulators are ones I personally have used on iOS.
More emulators for iOS can be found [here](https://emulation.gametechwiki.com/index.php/Emulators_on_iOS).
I do want to note that there are 2 programs which simulate iOS, [corellium](https://www.corellium.com) and [Apple's official sim](https://developer.apple.com/documentation/xcode/devices-and-simulator).

**Comment by DerekTurtleRoe** [comment]
@array-in-a-matrix I'm currently working on a large update adding a ton of new emulators, and I can add into the new emulators then. Thanks for these! 😄 

The ones that just need a platform update I can do when I get to their respective section.

**Comment by DerekTurtleRoe** [comment]
@array-in-a-matrix Thanks so much for your post! 😄 

I went through and added all platforms to existing emulators that weren't listed, and added the ones that were missing as well.

I am not able to add Happy Chick as it downloads ROMs, BIOS/firmware, and other copyrighted works by several game publishers and developers. It most likely won't be taken down since it is hosted in China, but for legal reasons I will avoid posting it here.

Thanks again for your contribution! 👍
